spring.application.name=BookAplication

server.port=8082

spring.h2.console.enabled=true
spring.datasource.username=root
spring.datasource.password=Password

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.file.name=logs/bookapp.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n
logging.level.root=INFO
logging.level.com.example.BookApplication=DEBUG
logging.logback.rollingpolicy.max-life-size=10MB
logging.logback.rollingpolicy.max-history=7